USE master
GO

IF NOT EXISTS(
	SELECT[name]
	FROM sys.databases
	WHERE [name] = 'MovieRentalsDB'
)

CREATE DATABASE MovieRentalsDB;
GO

USE MovieRentalsDB;
GO


CREATE TABLE Customers(
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Name VARCHAR (100) NOT NULL,
	PhoneNo VARCHAR (100) NOT NULL,
	Email VARCHAR (100),
	City VARCHAR (100) NOT NULL,
	Address VARCHAR (100),
);

CREATE TABLE Store (
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Location VARCHAR (100) NOT NULL,
);

CREATE TABLE Employees (
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	StoreID int NOT NULL FOREIGN KEY REFERENCES Store(ID),
	Name VARCHAR (100) NOT NULL,
	PhoneNo VARCHAR (100) NOT NULL,
	Email VARCHAR (100) NOT NULL , 
	City VARCHAR (100) NOT NULL,
	Address VARCHAR (100)NOT NULL,
);

CREATE TABLE Movies (
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MovieName VARCHAR (100) NOT NULL,
	Length VARCHAR (100) NOT NULL,
	Price int NOT NULL,
);

CREATE TABLE MoviesCategory (
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MovieID int NOT NULL FOREIGN KEY REFERENCES Movies(ID),
	Category VARCHAR (100) NOT NULL,
);

CREATE TABLE Rentals(
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CustomerID int NOT NULL FOREIGN KEY REFERENCES Customers(ID),
	MovieID int NOT NULL FOREIGN KEY REFERENCES Movies(ID),
	StoreID int NOT NULL FOREIGN KEY REFERENCES Store(ID),
	RentDate DATETIME NOT NULL DEFAULT GETDATE(),
);